---
# tasks file for ansible_role_nvml

- name: add nvidia CUDA repo
  ansible.builtin.yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"


- name: Switch DNF nvidia-driver stream to the chosen branch
  ansible.builtin.command:
    cmd: "dnf -y module enable nvidia-driver:{{ nvidia_driver_branch }}"
    
- name: install nvidia management library from rpm repository 
  ansible.builtin.dnf:
    name: "nvidia-driver-NVML"
    state: latest
