---
# tasks file for ansible_role_nvidia

- name: add nvidia CUDA repo
  ansible.builtin.yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    baseurl: "{{ nvidia_driver_rhel_cuda_repo_baseurl }}"
    gpgkey: "{{ nvidia_driver_rhel_cuda_repo_gpgkey }}"


- name: Switch DNF nvidia-driver stream to the chosen branch
  ansible.builtin.command:
    cmd: "dnf -y module enable nvidia-driver:{{ nvidia_driver_branch }}"

- name: install nvidia management library from rpm repository
  ansible.builtin.dnf:
    name: "{{nvidia_driver_nvml_package_name}}{{ '-' + nvidia_driver_version if nvidia_driver_version is defined else '' }}"
    state: latest
    install_weak_deps: "{{ nvidia_install_weak_deps }}"
  when: nvidia_install_nvml

- name: Make certain that libnvidia-ml.so-symlink exists
  ansible.builtin.file:
    src: /usr/lib64/libnvidia-ml.so.1
    dest: /usr/lib64/libnvidia-ml.so
    owner: root
    group: root
    state: link
  when: nvidia_install_nvml

- name: Install nvidia drivers
  block:

  - name: install precompiled nvidia drivers from rpm repository
    ansible.builtin.dnf:
      name:
        - "nvidia-driver{{ '-' + nvidia_driver_version if nvidia_driver_version is defined else '' }}"
        - "nvidia-driver-cuda{{ '-' + nvidia_driver_version if nvidia_driver_version is defined else '' }}"
  #    name: "@nvidia-driver:{{ nvidia_driver_branch }}"
      state: latest
      install_weak_deps: "{{ nvidia_install_weak_deps }}"

  - name: blacklist nouveau
    community.general.kernel_blacklist:
      name: nouveau
      state: present


  - name: create persistenced override dir
    ansible.builtin.file:
      path: /etc/systemd/system/nvidia-persistenced.service.d/
      state: directory
      recurse: yes

  - name: configure persistenced service to turn on persistence mode
    ansible.builtin.template:
      src: nvidia-persistenced-override.conf.j2
      dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
    when: nvidia_driver_persistenced

  - name: remove persistenced service override
    ansible.builtin.file:
      path: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
      state: absent
    when: not nvidia_driver_persistenced

  - name: enable persistenced
    ansible.builtin.systemd:
      name: nvidia-persistenced
      enabled: yes
    when: nvidia_driver_persistenced

  - name: set module parameters
    ansible.builtin.template:
      src: nvidia.conf.j2
      dest: "{{ nvidia_driver_module_file }}"
      mode: '0644'

  when: nvidia_install_driver
